### ISSUE TITLE
Model Deployment Standarization

### ISSUE THREAD

**Issue by ruhyadi** [ruhyadi/Model-Standarization-CVAT#1]
Clone Issue from [danilhendrasr/semi-automated-labeling/issues/13](https://github.com/danilhendrasr/semi-automated-labeling/issues/13)
Standarisasi model deployment ke CVAT (Nuclio). 
Problems:

- Dalam mendeploy model user harus membuat `function.yaml` dan `main.py`. Belum ada/sedikit dokumentasi tentang standarisasi pembuatan kedua file tersebut. Sehingga user harus membuat kedua file dengan menyesuaikan sesuai model yang ingin dideploy.
- Proses deployment masih berbasis script. Tidak praktis, karena user harus masuk ke directory cvat.

Proposal solution(s):
- [x] Standarisasi berbasis git repository (github, gitlab)
- [x] Standarisasi menggunakan Torch Hub
- [x] Prototype GUI Deployment model
- [x] Prototype GUI Upload Assets to Github Release #2 
- [ ] CI/CD checking torch hub #4
- [ ] CI/CD deploying to nuclio #5 
- [ ] Documentation pembuatan `function.yaml`
- [ ] Documentation pembuatan `main.py`
